### ISSUE TITLE
[dialogflow-generator]

### ISSUE THREAD

**Issue by vazquev** [GoogleCloudPlatform/contact-center-ai-samples#544]
In the final section of the [Informed decision making using Dialogflow CX generators and data stores](https://codelabs.developers.google.com/codelabs/dialogflow-generator) code lab, the check for weight does not work, I had to add the following line into the Generator text prompt to get it to work correctly:

"You are to ensure that the weight is correctly captured and compared against the weight requirement. Do this step by step." Once this was added, the weight was correctly compared against the requirement 

It also now works if I make it a few shot prompt:

Check the users eligibility against the following criteria: the minimum age is 18 and the maximum age is 75. The weight must be a minimum of 50 kg. The user is $age years old and weighs $weight Kg. You are to ensure that the weight is correctly captured and compared against the weight requirement
Here are a few examples:
Age = 19
Weight = 65 kg
Output = Eligible

Age = 19
Weight = 45 kg
Output = Not Eligible

Craft an email and politely explain to the user if they're eligible to donate and if not why.

**Comment by alessiasacchi** [comment]
Hi and thank you for checking out the codelab. I have just tested the below conversation through the agent chat window embedded into https://blood-donation-agent.web.app/. You are welcome to use it. 

**User:** Hi, I would like to find out if I am eligible to donate
**Agent:** To be eligible to donate blood, you must be 18-75 years old, healthy and weigh over 50 kg. You can take our blood eligibility quiz to find out if you are eligible.

**User:** Let's do it
**Agent:** How old are you?

**User:** I am 25
**Agent:** Are you pregnant or recently given birth?

**User:** no
**Agent:** Do you have a heart condition or/and are you low in iron?

**User:** no
**Agent:** What is your correct weight?

**User:** 40 kg

**Agent:** Subject: Blood Donation Eligibility

Dear [User Name],

I hope this email finds you well.

Thank you for reaching out to inquire about your eligibility to donate blood. We appreciate your willingness to help save lives through this selfless act.

Based on the information you provided during our conversation, you meet several criteria for blood donation. You are 25 years old, which falls within the acceptable age range of 18-75 years. You are also not pregnant or have recently given birth, which makes you eligible to donate. Additionally, you do not have any known heart conditions or iron deficiency, which are important factors in determining donor eligibility.

However, there is one criterion you do not meet: your weight is below the minimum requirement of 50 kg. Unfortunately, individuals weighing less than 50 kg are not eligible to donate blood due to safety concerns. This requirement ensures that the donation process does not pose any health risks to you or compromise the quality of the donated blood.

We understand that this news may be disappointing, but it is essential to prioritize the safety and well-being of both donors and recipients. If you are able to gain weight and reach the minimum requirement of 50 kg, we encourage you to reconsider donating in the future.

Thank you for your understanding and cooperation. Please do not hesitate to contact us if you have any further questions or concerns. We appreciate your interest in blood donation and hope that you will continue to consider it in the future.

Best regards,

[Your Name]
[Your Title/Position]
[Contact Information]

The agent detects and explains that the user's weight is below the allowed threshold and advises the user to reconsider donating blood in the future. 
I don't think there is an issue in the codelab. Having said that we are in a non-deterministic world so it is possible that the prompt suggested in the codelab didn't return the accurate eligibility answer once. Furthermore prompt engineering is an art so any "better and elegant" prompts are more than welcome. Thank you!
