### ISSUE TITLE
Ajuste en uno de los pasos

### ISSUE THREAD

**Issue by alejahenaoes** [GoogleCloudPlatform/contact-center-ai-samples#587]
En el paso 2, del nivel 7 del codelabs de 'Crea una app de chat generativo con Vertex AI Conversation'

Donde dice "Configuración de registro, habilita la opción Habilitar el registro de interacciones. Registro de interacciones en la configuración del agente" 

En la foto, el nombre pasó de Enable interaction logging a **Enable conversation history**

**Comment by koverholt** [comment]
Thank you for reporting this issue! There have been a number of changes to the product UI/UX since it was renamed from Vertex AI Search and Conversation to Vertex AI Agent Builder, so I appreciate you pointing this out. I've updated the screenshot and related text that you mentioned to refer to the new name of that setting. Readers can also refer to the [Vertex AI Agent Console documentation](https://cloud.google.com/dialogflow/vertex/docs) for the latest information.
